-- NEP Korea v49 기사 마감기능 DB 연결
-- Supabase SQL Editor에서 전체 실행하세요.

create table if not exists public.fuel_logs (
  id bigint generated by default as identity primary key,
  app_fuel_key text not null unique,
  fuel_date date not null,
  driver_id uuid references public.drivers(id) on delete set null,
  app_driver_id text not null,
  station text not null,
  liters numeric(10,2) not null default 0,
  cost bigint not null default 0,
  memo text,
  logged_at timestamptz,
  app_meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.factory_weigh_logs (
  id bigint generated by default as identity primary key,
  app_weigh_key text not null unique,
  weigh_date date not null,
  driver_id uuid references public.drivers(id) on delete set null,
  app_driver_id text not null,
  gross_kg numeric(12,2) not null default 0,
  tare_kg numeric(12,2) not null default 0,
  net_kg numeric(12,2) not null default 0,
  memo text,
  weighed_at timestamptz,
  app_meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists fuel_logs_driver_date_idx on public.fuel_logs(app_driver_id,fuel_date);
create index if not exists factory_weigh_logs_driver_date_idx on public.factory_weigh_logs(app_driver_id,weigh_date);

alter table public.fuel_logs enable row level security;
alter table public.factory_weigh_logs enable row level security;

drop policy if exists fuel_logs_authenticated_all on public.fuel_logs;
create policy fuel_logs_authenticated_all on public.fuel_logs for all to authenticated using (true) with check (true);

drop policy if exists factory_weigh_logs_authenticated_all on public.factory_weigh_logs;
create policy factory_weigh_logs_authenticated_all on public.factory_weigh_logs for all to authenticated using (true) with check (true);

-- v49의 수거 수정 기능은 기사 본인의 pickup_records를 수정/삭제해야 합니다.
drop policy if exists pickup_records_authenticated_all on public.pickup_records;
create policy pickup_records_authenticated_all on public.pickup_records for all to authenticated using (true) with check (true);

drop policy if exists route_stops_authenticated_update on public.route_stops;
create policy route_stops_authenticated_update on public.route_stops for update to authenticated using (true) with check (true);

notify pgrst, 'reload schema';
select 'v49 driver close DB ready' as result;
